### ISSUE TITLE
Pdbpp not respecting readline configuration (.inputrc)

### ISSUE THREAD

**Issue by antoine-gallix** [pdbpp/pdbpp#340]
Whenever I fall into Pdb++ debugger, the keybindings I defined in the readline configuration (`~/.inputrc`) is not respected anymore. Note that in the standard python interpreter, the keybindings are respected.

**Comment by blueyed** [comment]
Are you using pyrepl?
(and are you using pdbpp master - shouldn't really make a difference though I guess here)

**Comment by antoine-gallix** [comment]
I didn't willingly installed it, but indeed, there was `pyrepl` installed in my virtualenv, and I get back my keybindings as soon as I uninstall it. I consider my problem as solved. Do you know what common package has `pyrepl` as a dependency, or why it get used automanically instead of readline? In any case, thank you!

**Comment by blueyed** [comment]
pdbpp installs it.. :)

It's meant to be a replacement for readline, and apparently does not use its config.

I'm planning to make it an optional dep (also via install_requires), since it is quite a mess (was not working on py3 for a long time etc).
I recommend using ipython instead - e.g. using https://github.com/gotcha/ipdb will also use pdb++ inside of it, and you get completions via Jedi.
