### ISSUE TITLE
Show tracebacks in sticky mode

### ISSUE THREAD

**Issue by HudsonMC16** [pdbpp/pdbpp#432]
I'm not sure if I'm encountering a bug or intended behavior, but I have not found a way to display an error traceback when in sticky mode, and I've found visual indication of an unhandled exception and the entry of post-mortem debugging to be much too subtle. I've just been using the following simple program for testing:

```
print('Here we go!')
raise ValueError
```
When not in sticky mode, I get the full traceback and dumped to post-mortem debugging with statements indicating as much printed to the console. So far so good. Adding `sticky` to the top of the  pdbrc, however, does more-or-less the same thing, but without any helpful statements letting me know what's going on or the traceback. The only indication that I see that I've encountered an exception and entered post-mortem debugging is the `>>` in front of the line with the exception. Is there some setting I'm missing? 

I see some older issues and discussions indicating this package was only intended to support posix systems, and I am running Python 3.9 on Windows 10, but I wasn't sure if the current maintainer(s) were sticking to only supporting posix systems. Thank you!

**Comment by blueyed** [comment]
You might be able to see it when scrolling up the terminal history:
```
% python -m pdb t-432.py
[2] > …/src/pdbpp/t-432.py(1)<module>()
-> print('Here we go!')
(Pdb++) sticky
[2] > …/src/pdbpp/t-432.py(1)<module>()

1  -> print('Here we go!')
2     raise ValueError
(Pdb++) c
Here we go!
Traceback (most recent call last):
  File "/usr/lib/python3.9/pdb.py", line 1705, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.9/pdb.py", line 1573, in _runscript
    self.run(statement)
  File "/usr/lib/python3.9/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "…/src/pdbpp/t-432.py", line 1, in <module>
    print('Here we go!')
ValueError
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
[4] > …/src/pdbpp/t-432.py(1)<module>()

1  -> print('Here we go!')
2  >> raise ValueError
ValueError:
(Pdb++)
```

The problem here is kind of where the clearing of the screen happens.
Note that the above is from master.

Related commits:

- c58b798 (#368): Improve sticky mode
  This is basically what you would like to have.
- 352d928 (#370): sticky: keep clearing screen after "continue"
  This re-adds the extra clearing of the screen again.
  This can be questioned/challenged maybe, but the idea here is to keep the sticky mode at the top of the screen, but maybe/probably could take into account that there is (no) exception.
- be21980 (#381): Save "__exception__" with post mortem debugging (via main)
  This improves the `python -m pdb(pp)` / post-mortem use case (used by me above, not sure if that is what you're using), since it prints the exception before the prompt ("ValueError:")

I think given that the exception gets printed before the prompt (be21980, #381) is good enough for now, but we could revisit #370 with regard to not clearing the screen in case of an exception / post-mortem workflow.

(I've not checked how trivial this is to backport (either complete or #381 only, if that is helpful).
For now it is recommended to use pdb++ from the Git master branch).
