### ISSUE TITLE
when installing with pip --index-url is not respected 

### ISSUE THREAD

**Issue by ahmetctoker** [pdbpp/pdbpp#436]
I was trying to install `pdbpp` using a private pip mirror, residing in our  company data center. 

When I call `pip install --index-url=MIRROR_URL pdbpp`, I get the following error: 

```bash
Download error on https://pypi.org/simple/setuptools-scm/: [Errno 101] Network is unreachable -- Some packages may not be found!    Couldn't find index page for 'setuptools_scm' (maybe misspelled?)  
```
The pdbpp is downloaded from the Mirror. However, when building  `setuptools-scm` is searched in `pypi.org`, not in `--index-url`. 

I also tried using `pip` with the flags `--install-option="--index-url=MIRROR_URL"` and `--install-option="--find-links=MIRROR_URL"` without any success. 

This is probably a security issue according to `pip`:

> Be careful not to nullify all your security work when you install your actual project by using setuptools directly: for example, by calling python setup.py install, python setup.py develop, or easy_install. Setuptools will happily go out and download, unchecked, anything you missed in your requirements file—and it’s easy to miss things as your project evolves.

**Comment by blueyed** [comment]
I think this is more an issue of pip than pdbpp, isn't it?  What version is it?

(we're only using `setup_requires=['setuptools_scm']`, although I'd prefer to get rid of it - e.g. by something simpler / more straightforward to handle the (Git) version)

I'm closing the issue here already, but please feel free to follow up.
