### ISSUE TITLE
Cut a new release on pypi

### ISSUE THREAD

**Issue by morotti** [pdbpp/pdbpp#442]
Would it be possible to cut a new release on pypi?

Last release is 0.10.2 from October 2019. https://pypi.org/project/pdbpp/#history
Problem: that release doesn't work with current versions of python/ipython.

Personally, I had to remove pdbpp from all venv/projects because it broke stack traces and made debugging impossible. 

https://github.com/pdbpp/pdbpp/issues/397
https://github.com/pdbpp/pdbpp/issues/430
https://github.com/pdbpp/pdbpp/pull/426

Notice how bug reports end with "can't reproduce [in master]". Fixes may be in master however they won't be available to end-users until there is a release.

**Comment by gosella** [comment]
Oh, the synchronicity... I just came to ask for the same thing :smiley:

**Comment by blueyed** [comment]
See the pinned issue: https://github.com/pdbpp/pdbpp/issues/260 - there are many changes, and packaging needs to get addressed / fixed.

It would be possible to release from the `release-0.10` branch, but that also requires to fix CI (https://github.com/pdbpp/pdbpp/issues/441).
IIRC my plan was backporting https://github.com/pdbpp/pdbpp/pull/426 there.

Unfortunately I do not have much free time to work on pdb++ currently, but started with fixing CI last weekend though a bit.

> Fixes may be in master however they won't be available to end-users until there is a release.

It's not that hard to install/use it via `git+https` with pip after all.

**Comment by jugmac00** [comment]
For those who never installed a package from GitHub before: 

https://github.com/jugmac00/til/blob/master/python/install-release-candidates.md#github-1

Also the listed video (link above) explains this very well.

I just needed to install `pdb++` from GitHub in order to test the `pygments` formatter configuration from the README for #440 as this feature was added after the last release.

So, I am also looking forward to a new release very much.

Even after having a glimpse on #260, I certainly can't oversee what needs to be completed and why,  before a new release will be created, but I do not see much difference in creating a release from current master and/or asking users to install `pdb++` from current master. Certainly, a working CI is necessary, but you did already great work last weekend.

Or what do you think about an alpha release? This would be really great for the users, as an e.g. `pip install pdbpp=0.11a1` is certainly easier to handle than a `pip install git+https://github.com/pdbpp/pdbpp@b62a3381bd1db8fa3ffaa46579f477b187e2f37c`

It also would be easier to spread word about the upcoming version and ask users to alpha test the pre-release.

The current situation ( https://github.com/pdbpp/pdbpp/issues/260) seems really complicated for an outsider, so I do not think I could be of any help - except maybe testing.

That all said I am super grateful for your commitment and your spent spare time.

**Comment by blueyed** [comment]
JFI: I am working on getting the release-0.10 branch (`0.10.x`) back on track in https://github.com/pdbpp/pdbpp/pull/445.

**Comment by blueyed** [comment]
Started working towards releasing 0.10.3 in https://github.com/pdbpp/pdbpp/pull/447.
Will backport https://github.com/pdbpp/pdbpp/pull/426 there.
Let me know if there are more issues that should be fixed/backported there.

**Comment by alan-barzilay** [comment]
@blueyed 
>  Problem: that release doesn't work with current versions of python/ipython.

Maybe a stupid question but, does this mean that currently the only way to get pdbpp working is by cloning the main repo and that the version we would get through pip is broken?

**Comment by blueyed** [comment]
> @blueyed
> 
> > Problem: that release doesn't work with current versions of python/ipython.
> 
> Maybe a stupid question but, does this mean that currently the only way to get pdbpp working is by cloning the main repo and that the version we would get through pip is broken?

There are no stupid questions, only some that might get hidden as "Duplicate".. ;)
Yes, using pdbpp from PyPI is broken if you use it with IPython/ipdb, but since a while already.  Hopefully this is fixed soon with a new release then.

**Comment by blueyed** [comment]
0.10.3 has been released now.
