### ISSUE TITLE
pdb command  "commands" not working

### ISSUE THREAD

**Issue by asdf8601** [pdbpp/pdbpp#463]
Hi there,

I've tried to use `command` with and without sticky mode but I couldn't make it works.

I'm using:

1. python 3.6
2. pdbpp==0.10.3

# MRE

## main.py

```python
a = 0
for i in range(10):
    __import__("pdb").set_trace()
    a += i
```

Execution:

```
$ python main.py
(Pbd++) b 4
(Pbd++) commands
(com) print(a)
(com) end
(Pbd++) c
```

Nothing is printed... I'm missing something?

**Comment by 3outeille** [comment]
I noticed that if you are in sticky mode, printing does not work (but `commands` is working properly, try it on normal mode)

Edit: Seems to be the case indeed: https://github.com/pdbpp/pdbpp/issues/122

A quick hack when using normal mode, you can define the following alias in your `~/.pdbrc`:
`alias n list . ;; next # Overwrite n to list +/-5 lines around current line + next`

**Comment by blueyed** [comment]
Interesting issue, thanks for the report.

However, given the example file it also does not work with plain pdb, does it?
```
% python main.py
> /home/user/src/pdbpp/t/463/main.py(1)<module>()
-> a = 0
(Pdb) break 4
Breakpoint 1 at /home/daniel/src/pdbpp/t/463/main.py:4
(Pdb) commands
(com) print(a)
(com) end
(Pdb) c
> /home/user/src/pdbpp/t/463/main.py(4)<module>()
-> a += i
(Pdb) l
  1     a = 0
  2     for i in range(10):
  3         __import__("pdb").set_trace()
  4  ->     a += i
[EOF]
```

But when using this:
```python
a = 0
for i in range(10):
    a += i
```

```
% python -m pdb main.py
> /home/user/src/pdbpp/t/463/main.py(1)<module>()
-> a = 0
(Pdb) break 3
Breakpoint 1 at /home/daniel/src/pdbpp/t/463/main.py:3
(Pdb) commands
(com) print(a)
(com) end
(Pdb) c
0
> /home/user/src/pdbpp/t/463/main.py(3)<module>()
-> a += i
```

It also works on master in non-sticky mode:
```
% python -m pdbpp main.py
[2] > /home/user/src/pdbpp/t/463/main.py(1)<module>()
-> a = 0
(Pdb++) break 3
Breakpoint 1 at /home/user/src/pdbpp/t/463/main.py:3
(Pdb++) commands
(com++) print(a)
(com++) end
(Pdb++) c
0
[2] > /home/user/src/pdbpp/t/463/main.py(3)<module>()
-> a += i
(Pdb++)
```
(also when using `pdb -m pdb main.py`, and it behaves the same as pdb itself with the `set_trace` in the loop)

As for sticky mode I can see that it should e.g. not redraw after `commands`, and `end` (which it does for `end` on master, but not on the latest release).

With the clearscreen terminal sequence being replaced it looks like this:
```
% python main.py
[0] > …/src/pdbpp/t/463/main.py(2)<module>()
-> a = 0
(Pdb++) sticky

<CLEARSCREEN>
[0] > …/src/pdbpp/t/463/main.py(2)<module>()

1     __import__("pdb").set_trace()
2  -> a = 0
3     for i in range(10):
4         a += i
(Pdb++) break 4
Breakpoint 1 at …/src/pdbpp/t/463/main.py:4
(Pdb++) commands

<CLEARSCREEN>
[0] > …/src/pdbpp/t/463/main.py(2)<module>()

1     __import__("pdb").set_trace()
2  -> a = 0
3     for i in range(10):
4         a += i
(com++) print(a)
(com++) end

<CLEARSCREEN>
(Pdb++) c
0
[0] > …/src/pdbpp/t/463/main.py(4)<module>()
-> a += i
[0] > …/src/pdbpp/t/463/main.py(4)<module>()

1     __import__("pdb").set_trace()
2     a = 0
3     for i in range(10):
4  ->     a += i
(Pdb++)
```

So I think there's a general issue with it not working when `set_trace` is hit before again, likely because of some reset maybe, and could be fine-tuned for it to work better in sticky mode on master.

**Comment by blueyed** [comment]
This should be fixed via https://github.com/pdbpp/pdbpp/pull/464.
Might be worth investigating how a `set_trace` in the loop (re)set things to not work anymore, but that would be a new issue I think.
