### ISSUE TITLE
double spacing on truncate_long_lines False

### ISSUE THREAD

**Issue by strobelight** [pdbpp/pdbpp#488]
If `truncate_long_lines = False` in `.pdbrc.py`, when any one line needs wrapping (line 2 below), all the other non-comment lines appear double-spaced (or perhaps being needlessly wrapped too):

![DoubleSpacingTruncateFalseNarrow](https://user-images.githubusercontent.com/8398167/168820395-36c382c9-0ac7-4b09-a5ea-1ca7c2697a1d.png)

pdbpp version 0.10.3, Pygments version 2.12.0
osx iterm2 3.4.15 ssh into VM running screen, and TERM set to xterm-256color.

**Comment by blueyed** [comment]
This appears to be fixed on master.

ref: 412c5c202f0b13376cb18ea4d3fc9ef58e68066f (5e7d16a made it worse).

I still recommend using pdb++ from the master branch in general, and am sorry for not having cut a (major) release since a very long while.  Might be worth cherry-picking this into a bugfix release, but then it is also not a default setting.

Thanks for the report anyway, of course.

**Comment by strobelight** [comment]
Thanks, I simply did a `pip install ..` from my virtual environment, so I guess I get what I get.

edit: installed from master and can confirm the issue has been fixed.
