### ISSUE TITLE
TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by antocuni** [pdbpp/pdbpp#63]
Originally reported by: **Aurélien Campéas (Bitbucket: [auc](https://bitbucket.org/auc), GitHub: [auc](https://github.com/auc))**

----------------------------------------

```
#!python

  File "C:\Anaconda2\envs\py3k\lib\site-packages\_pytest\pdb.py", line 109, in post_mortem
    p.interaction(None, t)
  File "C:\Anaconda2\envs\py3k\lib\site-packages\pdb.py", line 244, in interaction
    self.print_stack_entry(self.stack[self.curindex])
  File "C:\Anaconda2\envs\py3k\lib\site-packages\pdb.py", line 798, in print_stack_entry
    print('[%d] >' % frame_index, file=self.stdout, end=' ')
  File "C:\Anaconda2\envs\py3k\lib\codecs.py", line 377, in write
    self.stream.write(data)
TypeError: write() argument must be str, not bytes
```

----------------------------------------
- Bitbucket: https://bitbucket.org/antocuni/pdb/issue/63

**Comment by henry-hsiao** [comment]
I met the same error. After searching for a while, I follow the reference and work around by modifying codecs.py: self.stream.write(data) to self.stream.write(data.decode('utf-8'))

ref: https://stackoverflow.com/questions/21689365/python-3-typeerror-must-be-str-not-bytes-with-sys-stdout-write 

Warning: I am okay with this modification. No guarantee for all cases using codes.py

**Comment by antocuni** [comment]
could you please write a failing test for it?

**Comment by henry-hsiao** [comment]
I think this issue may not be caused by pdbpp (pdbpp is a great debugging tool ! thank you). It is probably caused by the python 3.5 as discussed in the reference above. 

The failure case for me: I follow the "Docker image" part to build the docker image of the pytorch (https://github.com/pytorch/pytorch). And then I launch the docker. Running the commands below:

pip install pdbpp
python
import pdb
pdb.set_trace()

And the error is shown below, which is not exactly the same as the original post. I then modify the codes.py to work around the problem.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/bdb.py", line 52, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/bdb.py", line 93, in dispatch_return
    self.user_return(frame, arg)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/pdb.py", line 290, in user_return
    self.message('--Return--')
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/pdb.py", line 447, in message
    print(msg, file=self.stdout)
  File "/opt/conda/envs/pytorch-py35/lib/python3.5/codecs.py", line 377, in write
    self.stream.write(data)
TypeError: write() argument must be str, not bytes

**Comment by MarSoft** [comment]
Got the same problem as OP. My setup involves several different modules, not yet sure which of them causes the problem.
I am on Python 3.6.
Here is what I could find out so far:
1. Immediate error happens in `pdb.py` line `809`, in `print(('[%d] >' % frame_index, file=self.stdout, end=' ')`
2. I tried to set `pdb.set_trace()` above that line and found the following:
```
(Pdb) self.stdout
<encodings.utf_8.StreamWriter object at 0x7f777c790208>
(Pdb) sys.stdout
<_io.TextIOWrapper name='<stdout>' mode='w' encoding='ANSI_X3.4-1968'>
```
Please notice strange `encoding` on `sys.stdout`; I am not sure where did it come, as my system locale is `ru_RU.UTF-8`.

3. When trying to reproduce the problem using trivial test raising regular `ValueError`, with the same `set_trace` statement in place, got completely another state:
```
(Pdb) self.stdout
<_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
(Pdb) sys.stdout
<_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
```

So for me it looks like the problem is caused by output encoding changed for some unknown reason, which in its turn causes the system to use `StreamWriter` which doesn't tolerate `bytes` objects.
Investigating further.

**Comment by MarSoft** [comment]
Yes, this is almost true.

### Here is how to reproduce this error:
1. Create test file with the test raising any exception, like this
```
def test_error():
    raise ValueError
```
2. Run `py.test` **with locale set to some non-Unicode** (this is the key change). Like this:
`LANG=C py.test mytest.py`
3. Observe result:
```
...
E       ValueError

mytest.py:2: ValueError
======================================================================================= 1 failed in 0.23 seconds ========================================================================================
Traceback (most recent call last):
...
  File "/tmp/tmp.ou5kdfw1Va/lib/python3.6/site-packages/pdb.py", line 809, in print_stack_entry
    print('[%d] >' % frame_index, file=self.stdout, end=' ')
  File "/usr/lib/python3.6/codecs.py", line 377, in write
    self.stream.write(data)
TypeError: write() argument must be str, not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
  File "/tmp/tmp.ou5kdfw1Va/lib/python3.6/site-packages/_pytest/debugging.py", line 123, in post_mortem
    p.interaction(None, t)
  File "/tmp/tmp.ou5kdfw1Va/lib/python3.6/site-packages/pdb.py", line 252, in interaction
    self.print_stack_entry(self.stack[self.curindex])
  File "/tmp/tmp.ou5kdfw1Va/lib/python3.6/site-packages/pdb.py", line 809, in print_stack_entry
    print('[%d] >' % frame_index, file=self.stdout, end=' ')
  File "/usr/lib/python3.6/codecs.py", line 377, in write
    self.stream.write(data)
TypeError: write() argument must be str, not bytes
```

**Comment by MarSoft** [comment]
Not sure where is the problem - in pdbpp or in py.test. But "original" pdb still works in such situation.

**Comment by nip3o** [comment]
I have the same issue with Python 3.6.2 as well. This does however happen both with pytest as well as when using pdb in Django views.

The value of `$LANG` does not seem to matter for me, as I still get the error with `$LANG=en_US.UTF-8`. 
However, I also realized I also had `$PYTHONIOENCODING=utf_8` which shouldn't be needed in Python 3. Clearing this env variable solved the problem for me.

**Comment by FVolral** [comment]
I'm also having that problem on Python 3.5.2 using pdbpp 0.9.2 but it's seems even more radical since it's happening once I try to start pdb just after I imported it:
```

Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pdb
>>> pdb.set_trace()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Anaconda3\lib\bdb.py", line 52, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "C:\Program Files\Anaconda3\lib\bdb.py", line 93, in dispatch_return
    self.user_return(frame, arg)
  File "C:\Program Files\Anaconda3\lib\pdb.py", line 290, in user_return
    self.message('--Return--')
  File "C:\Program Files\Anaconda3\lib\pdb.py", line 447, in message
    print(msg, file=self.stdout)
  File "C:\Program Files\Anaconda3\lib\codecs.py", line 377, in write
    self.stream.write(data)
TypeError: write() argument must be str, not bytes
```

**Comment by blueyed** [comment]
@FVolral 
Do you use `PYTHONIOENCODING` or something similar?

**Comment by FVolral** [comment]
I don't think, PYTHONIOENCODING isn't listed in my os.environ.keys(). I used the work around of  @henry-hsiao and it worked :)

**Comment by blueyed** [comment]
Ok.
You are also using Python 3.5?

**Comment by FVolral** [comment]
Yes, Python 3.5.2 on Windows 7 64 bit and Anaconda. I hope that fix in codec.py won't break anything..

**Comment by KeynesYouDigIt** [comment]
Same issue here, working on codecs work around now

**Comment by KeynesYouDigIt** [comment]
lol works like a charm using @henry-hsiao 's workround

**Comment by FVolral** [comment]
in fact it worked like a charm until now but the fix can lead to that error when you try to write a file with a certain encoding:
`TypeError: a bytes-like object is required, not 'str'`

So, what I do is the following:         
```
if isinstance(data, str):
       self.stream.write(data.decode('utf-8'))
else:
       self.stream.write(data)
```

and it works like a charm again (until the next error)

**Comment by FVolral** [comment]
It's brings other errors.

The fix from @henry-hsiao seems to bring a bug when I do:
```
import codecs

with codecs.open('test.txt', 'wb', encoding='utf-8') as f:
    f.write("foo")
```

I got:
`TypeError: a bytes-like object is required, not 'str'`

Can someone confirm ? Also, by pritting the type of `self.stream`, I notice that it may differs. With my previous example, it is an instance of `<class '_io.BufferedWriter'>` when I launch pdb it is a  `<class '_io.TextIOWrapper'>` so it seems safer to do this instead:

```
if isinstance(self.stream, _io.TextIOWrapper):
    self.stream.write(data.decode('utf-8'))
else:
    self.stream.write(data)
```

Mainly, the type of `self.stream` in the write method of `StreamWriter ` may vary and, depending of its type, able or not to handle `str`. Since `data.decode('utf-8')` returns a `str`, it can crash in certain situation.  

That worked for me.

PS: Don't forget to `import _io` at the begining of` codecs.py`.

**Comment by blueyed** [comment]
What about upgrading to py36/py37 instead?

**Comment by FVolral** [comment]
yyess... but you kkknoww... *insert resistance to change argument here* ...

**Comment by blueyed** [comment]
Tested it with Python 3.5.3, pdbpp and pytest master, using `LANG=C .venv35/bin/pytest test_pytest.py --pdb`, based on https://github.com/antocuni/pdb/issues/63#issuecomment-322087390 (which appears to be using py36 however?!).

This would need some clear reproducible steps, which version information and (full) backtraces.

**Comment by Aloz1** [comment]
The issue appears to specifically stem from [here](https://github.com/antocuni/pdb/blob/654bcdac435b0bad8e324cd3a0b7bf857b0880ec/pdb.py#L190).

It's triggered whenever the 'encoding' attribute of the underlying stream object (generally `sys.stdout`) returns any encoding other than `utf-8`. This will happen when setting PYTHONIOENCODING (note, [comment #63](https://github.com/antocuni/pdb/issues/63#issuecomment-329125092) has miss-spelled it `utf_8`, hence why they're also affected) or when running python under Windows (which has an encoding of `cp850`).

The `StreamWriter` class that is retrieved by `codecs.getwriter` internally calls `write` with a `bytes` object as an argument to the underlying file-object. Under Python 3, `sys.stdout`'s `write` method only accepts strings, not bytes.

Changing the line to `f = codecs.getwriter('utf-8')(f.buffer)` seems to fix the issue for me.

[See here for an SO reference](https://stackoverflow.com/questions/4374455/how-to-set-sys-stdout-encoding-in-python-3)

**Comment by blueyed** [comment]
@Aloz1 
Thanks for the detailed investigation.  https://github.com/antocuni/pdb/pull/126 should fix it.

**Comment by blueyed** [comment]
To everyone affected: please test https://github.com/antocuni/pdb/pull/126, and I will cut a release with it then soon.
