### ISSUE TITLE
tab doesn't start autocomplete

### ISSUE THREAD

**Issue by liavkoren** [pdbpp/pdbpp#74]
The prompt is correct, `(Pdb++)`, but a tab just moves the cursor over to the right. Possibly a readline issue on my system?

**Comment by blueyed** [comment]
Do cursor keys work for you?

I am seeing `^[[D` etc for them in a *nested* pdb++ (via `debug some_call()`).
I have not investigated (since it does not happen that often that I use it), but it might be related?!
Mine is likely more an issue of `stdin` or something else from the terminal not being forwarded to the inner pdb?!

**Comment by liavkoren** [comment]
Yes, cursor keys work. : ) I'm entering pdb via `pdb.set_trace()`.

**Comment by antocuni** [comment]
if you press `TAB` on an **empty** pdb++ prompt, it is expected to insert an actual TAB. You need to type something to trigger completion; e.g., try to type `str.<TAB>`.

This is actually a feature a `fancycompleter`: maybe not very useful for pdb++, but if you use `fancycompleter` with a standard python prompt, it lets you to use `TAB` for indentation.

**Comment by liavkoren** [comment]
Yes, I know. : ) I was trying to autocomplete names I'd already started.

**Comment by antocuni** [comment]
I think I need some more info to be helpful: which OS/platform are you using?
Does `fancycompleter `work? E.g.:

```pycon
>>> import fancycompleter
>>> fancycompleter.interact()
>>> str.<TAB>
```

**Comment by liavkoren** [comment]
Oh, sorry, of course. I've run into this on a few different recent versions of OS X. Currently on 10.12.5. Py3.6.2
```
(Pdb++) import fancycompleter
(Pdb++) fancycompleter.interact()
(Pdb++) str.    
```
Just tabs the cursor over. : ) 

pip freeze of the current venv, but I've had this happen in other venvs, too:
```
appnope==0.1.0
decorator==4.1.2
docopt==0.6.2
fancycompleter==0.8
ipython==6.2.1
ipython-genutils==0.2.0
jedi==0.11.0
numpy==1.10.4
parso==0.1.0
pdbpp==0.9.2
pexpect==4.3.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
-e git+https://github.com/jonathanslenders/ptpython.git@da2c5281f60c2d8a92749709219771ffaa84220f#egg=ptpython
ptyprocess==0.5.2
Pygments==2.2.0
simplegeneric==0.8.1
six==1.11.0
traitlets==4.3.2
wcwidth==0.1.7
wmctrl==0.3
```

**Comment by antocuni** [comment]
Ok, I don't have an OS X to try by myself, but I think it might be related to this:
https://bitbucket.org/antocuni/fancycompleter/src/22e3669eeeb48134ea6df1114ec7d70415d4cafc/fancycompleter.py?at=default&fileviewer=file-view-default#fancycompleter.py-334

in particular, note the `python3? just return False for now` comment. What happens if you turn it into `return True`?

**Comment by liavkoren** [comment]
Okay! So, toggling the bit returned by `has_leopard_libedit` worked in the venv that I started this issue with. 

However, in a *different* py3 venv, just entering a breakpoint with pdbpp caused a malloc error in python upon exiting pdb:

```
(Pdb++)
Python(58609,0x7fffa35223c0) malloc: *** error for object 0x100522f20: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```
The error goes away if I uninstall pdbpp.
Would you like me to open a separate issue about that? 
(sorry, I'm breaking all your stuff.. )

**Comment by antocuni** [comment]
So, I tried to fix `fancycompleter` so that it correctly detects `libedit` also on py3k; however, since I don't have access to any OS X machine, I had to do it blindly; could you please try this and tell me if it works:
https://bitbucket.org/antocuni/fancycompleter/commits/7499f06fd3948566acaa02cb7b1290af914cc441

As for the malloc issue: I am tempted to say that it has nothing do to with pdb or pdbpp but it's a bug in some module which you are using. It is very likely that the memory is corrupted anyway, and starting pdb simply shuffles things enough to cause this specific error (but it could also be a segfault, or anything else for all I know).

**Comment by theY4Kman** [comment]
FYI: your fix for fancycompleter did the trick for me on my also-broken OSX. However, on py3, it does complain about trying to do an `string in bytes_object` comparison:
```pytb
  File "/Users/they4kman/.virtualenvs/shlamawhamadingdong/lib/python3.6/site-packages/fancycompleter.py", line 343, in has_leopard_libedit
    if p.returncode == 0 and 'libedit' in stdout:
TypeError: a bytes-like object is required, not 'str'
```

I changed it to:
```py
if p.returncode == 0 and 'libedit' in stdout.decode('utf-8'):
```

**Comment by theY4Kman** [comment]
As a workaround, you can install [my fork](https://github.com/theY4Kman/fancycompleter) of fancycompleter with [antocuni's patch](https://github.com/antocuni/pdb/issues/74#issuecomment-346999806) and py3 fix:
```
pip install git+https://github.com/theY4Kman/fancycompleter.git#egg=fancycompleter
```

**Comment by blueyed** [comment]
Closing this since it a bug with fancycompleter.

@theY4Kman / @antocuni 
Please incorporate the patch there.
As for the `stdout.decode('utf-8')` this might not work for non-utf8 encodings, of course.

**Comment by antocuni** [comment]
I incorporated the patch on fancycompleter: https://bitbucket.org/antocuni/fancycompleter/commits/046686b75bc032cf6d8d8286f1c1a38de3fe5247

however, I am having troubles with bitbucket pipelines and cannot do a release at the moment :(

**Comment by msabramo** [comment]
@antocuni: Need help with the release?

**Comment by blueyed** [comment]
@msabramo 
It would be great if we could get fancycompleter also on track again - the best would be to also move it over to Github I think.

**Comment by blueyed** [comment]
JFI: fixed in https://github.com/pdbpp/fancycompleter/pull/4.
